import "./globals.css";
import "sweetalert2/dist/sweetalert2.min.css";

import type { Metadata } from "next";
import { Tajawal } from "next/font/google";

import Footer from "@/components/Global/Footer/Footer";
import GMeta from "@/components/Global/GMeta";
import Header from "@/components/Global/Header/Header";
import Container from "@/components/Providers/Container";

export const metadata: Metadata = {
  title: "Shoppzila",
  description: "Generated by create next app",
};

const TJ = Tajawal({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GMeta
        title="Shoppzila: Your Ultimate Shopping Destination for Quality and Convenience"
        author="bimventures"
        desc="At Shoppzila, we're more than just a shopping website; we're your go-to haven for all things fashion, electronics, home essentials, and more. With an extensive range of products, seamless navigation, and a commitment to delivering exceptional customer experiences, Shoppzila is your one-stop-shop for all your needs."
        keys="Discover a World of Choice,Unparalleled Convenience,Quality and Authenticity"
      />
      <body className={TJ.className}>
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
