export const PRODUCTS_GETTER_SUB = "PRODUCTS_GETTER_SUB";
export const PRODUCTS_GETTER = "PRODUCTS_GETTER";
export const PRODUCT_GETTER = "PRODUCT_GETTER";
export const CATEGORY_GETTER = "CATEGORY_GETTER";
export const BOXES_GETTER = "BOXES_GETTER";
